<?php

namespace GovWiki\DbBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatRepository extends EntityRepository
{
    /**
     * @param integer $government A Government entity id.
     * @param integer $user       A User entity id.
     *
     * @return boolean
     *
     * @throws NonUniqueResultException
     */
    public function isMember($chat, $user)
    {
        $expr = $this->_em->getExpressionBuilder();

        try {
            return $this->createQueryBuilder('Government')
                ->addSelect('User')
                ->leftJoin('Government.subscribers', 'User')
                ->where($expr->andX(
                    $expr->eq('Government.id', ':government'),
                    $expr->eq('User.id', ':user')
                ))
                ->setParameters([
                    'government' => $government,
                    'user'       => $user,
                ])
                ->getQuery()
                ->getSingleResult() !== null;
        } catch (NoResultException $e) {
            return false;
        }
    }
}
