<?php

namespace GovWiki\DbBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * IssuesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssuesRepository extends EntityRepository
{

    /**
     * @param integer $government A government entity id.
     * @param integer $year       Data year.
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getListQuery($government, $year)
    {
        $expr = $this->_em->getExpressionBuilder();
        $qb = $this->createQueryBuilder('Issue')
            ->where($expr->andX(
                $expr->eq('Issue.government', ':government'),
                'YEAR(Issue.date) = :year'
            ))
            ->setParameters([
                'government' => $government,
                'year' => $year,
            ]);

        return $qb;
    }
}
