<?php

namespace GovWiki\DbBundle\Doctrine\Manager;

use Doctrine\ORM\Decorator\EntityManagerDecorator;

/**
 * Class GovWikiEntityManager
 * @package GovWiki\DbBundle\Doctrine\Manager
 */
class GovWikiEntityManager extends EntityManagerDecorator
{
    public function getRepository($className)
    {
        return parent::getRepository($className); // TODO: Change the autogenerated stub
    }

}
